### ISSUE TITLE
[JOSS Review] Community guidelines

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#11]
[Ref https://github.com/openjournals/joss-reviews/issues/541#issuecomment-359456428]

The contributing section of the docs is pretty good.  I have a couple of minor suggestions though:

- Add an explicit section for people seeking support.  This is distinct from contributing, and should be easy to find.
- Consider copying the contributing doc as `CONTRIBUTING.md` on github.  [This blog post](https://github.com/blog/1184-contributing-guidelines) describes that GH will find and link this directly.

**Comment by boisgera** [comment]
- Yeah, good one; I'll add a (short) section for people seeking support directly in the README, so that they don't have to search in the documentation.

  - I knew about CONTRIBUTING.md but I am not a big fan of it. If I could bypass the "GitHub way" and directly declare the url of the Contributing section in the docs, and that link would be displayed when a user writes an issue, that would be great. But here I would have to duplicate the file (urk ...), convert between different markdown flavors (urk ...), rewrite the relative links, etc.
