### ISSUE TITLE
Numpy is a requirement

### ISSUE THREAD

**Issue by edupo** [boisgera/bitstream#18]
When installing from PyPI in a clean environment (Docker -> python:3.6) next exception raises.
```
 Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-wya_8868/bitstream/setup.py", line 33, in <module>

        raise ImportError(error)

    ImportError: numpy not available. Try the command 'pip install -m numpy' or use a pre-built package for your operating system.
```

I believe this package not only supports `numpy` but depends on it so it must be added to it's requirements.

**Comment by boisgera** [comment]
Yes, indeed ; the quickstart mentions that NumPy should be installed beforehand :  https://github.com/boisgera/bitstream#quickstart .
Tehnically, I cannot just add NumPy as a dependency in the setup.py (in the `setup` function) since I need the numpy header before the execution of the `setup` function (see `numpy.get_include()` in `make_extension`). This is a clasic issue with extension modules (implemented in C). AFAICT (things may have changed ?) the simplest way to deal with this is to require NumPy to be installed beforehand.

**Comment by edupo** [comment]
I see. Thanks for the tip.
