### ISSUE TITLE
[JOSS Review] Improve API docs for State object

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#7]
[Reference https://github.com/openjournals/joss-reviews/issues/541#issuecomment-359456428]

The documentation for the `State` object does not provide much in the way of detail.  I understand that this is primarily an internal-facing class, but it should still be documented for the sake of future developers.

**Comment by boisgera** [comment]
The absence of API is a feature :) ... since this is an [opaque type](https://en.wikipedia.org/wiki/Opaque_data_type). In other words, the *user* should not rely on any implementation detail to be safe: it can only produce one with `save`, store it somehow and if needed give it to `restore`.

That being said:

  - the mere mention of  "(opaque) type" in the documentation is probably not good enough for the user.
    I have added a link to wikipedia, let me know if you think that I should be more explicit.

  - mostly for the developers, I have added a (sketchy) discussion of the internals in the Snapshot section: <http://boisgera.github.io/bitstream/snapshots/#how-does-it-work>. Does it help?

Commit: 0a84d53119f243648ae08a37ab0fce58bab302e3

**Comment by bmcfee** [comment]
How about just saying in the docs that the `State` object is meant for internal use only, and not meant for users?  That seems more direct than making a user follow a link and read an article, only to eventually discover that the class they're reading about isn't meant for them in the first place.

**Comment by boisgera** [comment]
But it is meant for users if they want to develop algorithms that "roll back" stream read or writes.
Arguably, this is an advanced pattern that most users won't need; and it only starts to make sense I guess if you look at this part of the API after having read the Snapshot section.
OTOH, its *implementation* is an internal detail.
I am dropping the link (yep, doesn't help much) and trying to explain this concisely.

**Comment by bmcfee** [comment]
I guess my personal preference would be to document it anyway (for the sake of developers, including future-you), but it's not a hard preference, so I understand if you prefer to keep it this way.
